base_url = "http://127.0.0.1:8000"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "css"
smart_punctuation = true

[extra]
footer_text = "Website built using [Zola](https://www.getzola.org) and the [Academic Workshop](http://github.com/aterenin/academic-workshop/) theme."
title = {tagline = "", title = "AI-PDE Workshop: ACC 2026", subtitles = ["AI for Modeling, Control, and Optimization of Partial Differential Equations"]}
banner = {extension = "svg", size = "fixed", fade = true}
buttons = [{name = "Homepage", url = ""}]
image = {resize = 400, ext = '.jpg'}
list_page_limit = 10
header_pages = [{name = "Home", url = "/#home"},{name = "Design", url = "/#design"}]
button_shortcuts = [{variable = "video", name = "Video"}]
